import type { MetadataRoute } from "next";
import type { Market } from "@lavion/schema";
import { getAllSlugs } from "@/lib/listings";

const MARKETS_LIST: Market[] = ["uk", "ae", "pk"];

/**
 * In production this is generated by a scheduled job on the KVM4 box and split
 * per market, not computed per request — a portal sitemap gets large fast.
 * This route is the development and small-scale path.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
  const slugs = await getAllSlugs();

  const roots: MetadataRoute.Sitemap = MARKETS_LIST.map((m) => ({
    url: `${base}/${m}`,
    changeFrequency: "daily",
    priority: 0.9,
    alternates: {
      languages: Object.fromEntries(MARKETS_LIST.map((x) => [`en-${x.toUpperCase()}`, `${base}/${x}`])),
    },
  }));

  const searches: MetadataRoute.Sitemap = MARKETS_LIST.map((m) => ({
    url: `${base}/${m}/search`,
    changeFrequency: "hourly",
    priority: 0.8,
  }));

  const properties: MetadataRoute.Sitemap = slugs.map(({ market, slug }) => ({
    url: `${base}/${market}/property/${slug}`,
    changeFrequency: "weekly",
    priority: 0.7,
  }));

  return [
    { url: base, changeFrequency: "weekly", priority: 1 },
    ...roots,
    ...searches,
    ...properties,
  ];
}
