import type { MetadataRoute } from "next";
import { MARKETS, type Market } from "@lavion/schema";
import { getAreaGuide, getAreaTaxonomy } from "@/lib/areas";
import { allGuideParams } from "@/lib/guides";
import { getAllSlugs } from "@/lib/listings";

const MARKETS_LIST: Market[] = ["uk", "ae", "pk"];

/**
 * In production this is generated by a scheduled job and split per market, not
 * computed per request — a portal sitemap gets large fast. This route is the
 * development and small-scale path.
 *
 * Only indexable area guides are listed. Submitting a URL that carries
 * `noindex` wastes crawl budget and sends a contradictory signal, so the
 * sitemap and the robots meta tag are driven by the same threshold.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
  const slugs = await getAllSlugs();
  const taxonomy = await getAreaTaxonomy();

  // Real BCP-47 locales from the schema: the UK's region subtag is GB.
  const languages = Object.fromEntries(
    MARKETS_LIST.map((m) => [MARKETS[m].locale, `${base}/${m}`]),
  );

  const roots: MetadataRoute.Sitemap = MARKETS_LIST.map((m) => ({
    url: `${base}/${m}`,
    changeFrequency: "daily",
    priority: 0.9,
    alternates: { languages },
  }));

  const searches: MetadataRoute.Sitemap = MARKETS_LIST.map((m) => ({
    url: `${base}/${m}/search`,
    changeFrequency: "hourly",
    priority: 0.8,
  }));

  const submit: MetadataRoute.Sitemap = MARKETS_LIST.map((m) => ({
    url: `${base}/${m}/submit`,
    changeFrequency: "monthly",
    priority: 0.6,
  }));

  // Area guides — indexable ones only.
  const guides: MetadataRoute.Sitemap = [];
  for (const t of taxonomy) {
    const guide = await getAreaGuide(t.market, t.citySlug, t.localitySlug);
    if (!guide?.indexable) continue;
    guides.push({
      url: t.localitySlug
        ? `${base}/${t.market}/for-sale/${t.citySlug}/${t.localitySlug}`
        : `${base}/${t.market}/for-sale/${t.citySlug}`,
      changeFrequency: "daily",
      priority: t.localitySlug ? 0.75 : 0.85,
    });
  }

  const guidePages: MetadataRoute.Sitemap = [
    ...MARKETS_LIST.map((m) => ({
      url: `${base}/${m}/guides`,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
    ...(await allGuideParams()).map((g) => ({
      url: `${base}/${g.market}/guides/${g.slug}`,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    })),
  ];

  const properties: MetadataRoute.Sitemap = slugs.map(({ market, slug }) => ({
    url: `${base}/${market}/property/${slug}`,
    changeFrequency: "weekly",
    priority: 0.7,
  }));

  return [
    { url: base, changeFrequency: "weekly", priority: 1, alternates: { languages } },
    ...roots,
    ...searches,
    ...guides,
    ...guidePages,
    ...submit,
    ...properties,
  ];
}
